project_name: pmve
before:
  hooks:
    - go mod tidy
dockers:
  - image_templates:
      - "ghcr.io/chumper/pmve:{{ .Tag }}"
      - "ghcr.io/chumper/pmve:v{{ .Major }}"
      - "ghcr.io/chumper/pmve:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/chumper/pmve:latest"
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
