name: GoReleaser

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    -
      name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - 
      name: Run GoReleaser Action
      uses: goreleaser/goreleaser-action@v2.7.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
